import TabMenu from "../tab-menu/TabMenu";
import Style from './BurgerIngredients.module.css';

function BurgerIngredients() {
  return(
    <>
      <TabMenu />
      <div className={Style.main}>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis velit nulla, feugiat eleifend ligula non, egestas interdum lectus. Etiam maximus cursus nisi a fringilla. Quisque ut risus ac massa condimentum vehicula. Donec scelerisque ligula sit amet dui fringilla, a efficitur mi sagittis. Cras a consequat lectus. Integer lacinia risus non lorem fringilla, et gravida erat lobortis. Ut mollis purus sem, semper ultricies lacus mattis quis. Donec ac sem nec nisl porttitor feugiat. Pellentesque id convallis orci. Sed sem orci, porta vehicula lacinia vitae, mattis vitae nibh. Sed non lectus sit amet nunc placerat finibus sollicitudin ut nibh. Suspendisse a velit imperdiet nisi rutrum ornare. In consectetur euismod felis, sit amet lobortis mi tristique nec. Aenean at magna sem.

In ullamcorper vehicula maximus. Morbi commodo pharetra risus quis ullamcorper. Maecenas vel fermentum est. Etiam cursus lacus erat, sed finibus eros pellentesque varius. Nam lobortis, est nec tincidunt egestas, dui mi consectetur nunc, et molestie mauris felis eu mi. Cras vel purus at nulla venenatis pretium. Donec facilisis, risus vel euismod eleifend, risus nulla efficitur orci, et maximus magna metus ut est. Sed porta auctor elit, vitae consectetur tortor mollis a. Donec ac nibh lobortis, tincidunt sapien nec, finibus elit. Suspendisse cursus faucibus mollis. Phasellus commodo lectus eget tristique auctor. Maecenas ultricies, est id iaculis aliquet, odio tortor auctor elit, quis egestas nunc nulla vel nulla. Praesent in euismod lectus, ut vehicula dui. Mauris et facilisis erat.

Etiam vitae mi faucibus, mollis leo vel, aliquam neque. Proin condimentum sapien id tortor pretium ultrices. Sed sed mi ut neque rutrum aliquam eu sed nisl. Fusce eu commodo velit, et iaculis nisl. Curabitur tincidunt elementum commodo. Duis at pharetra arcu, non aliquam tortor. Aliquam sed diam commodo, interdum diam quis, tempus nisl. Nulla quis leo tincidunt lorem posuere hendrerit non nec purus. Mauris accumsan dapibus porttitor. Cras rhoncus orci quis volutpat faucibus.

Fusce gravida volutpat mi, ac porttitor purus placerat in. Ut ut lorem lobortis, sodales erat non, consequat sem. Ut pulvinar justo lacus, eu viverra orci semper eu. Cras vitae massa ipsum. Curabitur auctor ante et ultrices sodales. Pellentesque augue quam, dapibus sit amet ultrices et, pellentesque vitae sem. Aenean id metus non mi viverra ultricies eget ut elit. Nam et libero vitae felis vestibulum imperdiet eu consectetur ex. Aliquam tincidunt faucibus arcu, vitae suscipit risus blandit vel. Suspendisse metus orci, condimentum quis dictum in, ornare ac sapien. Nulla tempus orci at odio ultricies congue. Nunc id leo ligula. Proin at ex posuere, faucibus libero eu, tincidunt odio. Curabitur sed ornare massa, sed fermentum urna. Quisque id auctor odio.

Nam venenatis rhoncus lectus, quis pretium elit placerat non. Cras suscipit convallis viverra. Etiam non laoreet diam. Fusce non convallis neque. Sed bibendum velit mauris, in rhoncus turpis dictum non. Sed maximus nunc nulla, vel scelerisque nulla finibus non. Morbi accumsan mattis nulla vel faucibus. Etiam rhoncus faucibus rutrum. Nullam et nisl consequat, laoreet justo ut, imperdiet lectus. Phasellus convallis faucibus auctor. Phasellus eget metus quis eros varius commodo eu at lacus. Vestibulum mattis mi leo, vel auctor urna finibus et.

Vivamus aliquam sollicitudin nulla id tempor. Integer sit amet sapien in tortor tincidunt egestas at sed nulla. Cras accumsan ante non dapibus varius. Suspendisse varius dolor dui, quis pharetra nisi dapibus nec. Donec pellentesque, neque quis interdum bibendum, sapien tortor pretium lorem, id pretium ipsum lacus vel elit. Morbi eu quam non quam tincidunt tincidunt a eu elit. Duis quis ex rutrum orci tincidunt consequat. Nunc dapibus turpis finibus lorem iaculis posuere. Praesent id tristique purus, et molestie lectus. Duis elementum metus id dolor posuere venenatis. Aliquam augue elit, sollicitudin id iaculis nec, sollicitudin et nunc. Morbi turpis nisl, bibendum scelerisque purus sit amet, egestas malesuada lectus. Phasellus commodo commodo libero, quis pharetra lacus condimentum mollis.

Aliquam accumsan tortor ut risus convallis condimentum. Vivamus laoreet sapien sed posuere iaculis. Pellentesque aliquam libero eu sem eleifend fringilla. Duis arcu diam, pretium at justo vel, rutrum vehicula est. Ut commodo, nibh nec faucibus lacinia, nulla metus ornare felis, in aliquet enim dui ac mi. Cras quis felis sit amet lorem viverra maximus id ut tortor. Praesent semper arcu a eros porta, nec tristique leo malesuada. Vivamus lorem dolor, facilisis vitae convallis nec, imperdiet pharetra nibh. Sed et vehicula ipsum. Aenean orci velit, fringilla vel sollicitudin feugiat, tincidunt tempor libero. Praesent sit amet elit pellentesque, imperdiet nulla ac, accumsan nulla. Ut tincidunt aliquam nisl, nec suscipit dolor aliquam eget. In commodo, justo id hendrerit iaculis, eros tellus tristique eros, sit amet faucibus felis mi quis quam. Maecenas sit amet nunc quis turpis convallis tristique molestie in leo.

Ut imperdiet rutrum ultrices. Integer et metus ac risus elementum hendrerit ac non purus. Praesent nec turpis consectetur, varius erat in, facilisis nisi. Ut egestas faucibus lectus in facilisis. Vivamus congue maximus mi, id eleifend lorem scelerisque vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu faucibus ante, at auctor nulla. Pellentesque dignissim ipsum sed dui maximus porta. Donec porta quis purus ut pharetra.

Phasellus sed dignissim felis, consectetur fringilla magna. Suspendisse sit amet risus tellus. Pellentesque faucibus nisl sit amet lacus rutrum, at tempus nulla auctor. Mauris nec molestie enim, vitae dictum quam. Ut placerat quam ex, sit amet semper odio fringilla non. Sed sollicitudin ultrices porta. Mauris tortor tortor, dictum a pellentesque a, viverra at sapien. Pellentesque condimentum ut mauris nec facilisis. Aliquam sed efficitur nibh, sed tristique orci.

Duis pellentesque varius ex a pharetra. Vestibulum eu sodales diam. Integer faucibus, ante id interdum rutrum, dui dolor congue tellus, sit amet feugiat neque mi id nisl. Quisque sodales nisl dapibus, consequat dolor tincidunt, bibendum nibh. Ut tempus metus eget eros tincidunt ullamcorper. Praesent ornare blandit luctus. Pellentesque feugiat ipsum urna, a suscipit eros feugiat convallis. Suspendisse rutrum magna luctus, vehicula neque pharetra, porttitor purus. Quisque imperdiet tellus fringilla varius egestas. Nam sapien lacus, cursus nec rutrum quis, rhoncus a erat.

Suspendisse aliquet posuere odio, eu pretium tellus rhoncus id. Aenean mollis, enim sit amet accumsan tempus, massa enim fermentum lorem, vel fringilla ex velit ut lectus. Etiam sit amet quam dui. Quisque porttitor metus non suscipit ullamcorper. Vestibulum lacinia facilisis sapien, ullamcorper tincidunt augue. Pellentesque sit amet placerat leo, non lobortis dolor. Aenean fringilla aliquam sem, sit amet semper libero sagittis quis. Nullam varius mattis pellentesque. Pellentesque tincidunt dignissim risus tincidunt dictum. Vivamus sed quam eu dui tempor pharetra. Aenean luctus eu est sed ultrices. Etiam eu elit sem. Nullam ligula sem, egestas non dignissim nec, commodo sed nisi. In a nisi vulputate, vehicula arcu non, cursus urna.

Pellentesque tincidunt, metus lobortis blandit malesuada, ligula elit consequat magna, vel venenatis velit orci in nulla. Mauris varius sem nunc, ac tincidunt justo mattis ac. Curabitur fermentum, diam et lacinia interdum, mauris mauris auctor mi, sit amet cursus mauris quam at ipsum. Duis sit amet dui in arcu sollicitudin vulputate. Suspendisse consectetur maximus sem, nec ullamcorper est auctor ac. Vestibulum augue nisi, tincidunt nec malesuada et, lobortis non ligula. Integer lorem lorem, dapibus vel nulla id, finibus malesuada odio. Ut vel tellus nunc.

Proin tincidunt quis sapien quis tempus. Sed dignissim molestie diam, nec elementum turpis ultricies eget. Ut semper, velit non consectetur rutrum, turpis ipsum ultrices dolor, suscipit scelerisque urna neque sit amet risus. Vestibulum aliquet lectus et rhoncus congue. Sed blandit sodales dignissim. Nam sollicitudin metus ut faucibus lobortis. Ut sagittis non mi at fringilla. Vivamus convallis quis ex ac ultricies. Sed dolor erat, porttitor posuere scelerisque vitae, luctus eget mauris.

Vivamus pulvinar vehicula purus a euismod. Vivamus ac malesuada mauris, vel condimentum ante. Integer pharetra, nisl eget rutrum condimentum, diam nibh tempus quam, a accumsan augue lorem et eros. Etiam vel odio enim. Cras magna odio, interdum quis varius eget, bibendum id velit. Aliquam vitae semper lorem, sed placerat ex. Nulla pellentesque augue id libero pharetra, a consectetur tortor tempor. Integer id ante fermentum, faucibus augue a, posuere massa. Suspendisse ut est neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris sit amet nunc lorem. Phasellus at sem sed justo efficitur fringilla sit amet eget urna. Praesent at ipsum ipsum.

Aliquam et purus sem. Praesent eleifend molestie enim, a consectetur lectus blandit a. Aenean eu massa lorem. Etiam interdum, enim sagittis aliquam ullamcorper, ex dui scelerisque quam, at mollis ipsum orci ac purus. Vestibulum vestibulum fermentum diam posuere imperdiet. Duis orci nisl, gravida vitae mauris id, viverra ultricies lectus. Aenean laoreet ultrices pulvinar. Donec vitae ullamcorper risus. Praesent nisi sem, maximus id purus id, placerat suscipit felis. Morbi imperdiet sem odio.

In hendrerit et elit at congue. Nam consequat felis convallis massa pharetra, vestibulum imperdiet est malesuada. Ut euismod luctus enim non malesuada. Integer vestibulum fermentum pharetra. Suspendisse potenti. Curabitur lacus justo, placerat sed mollis ut, faucibus sodales felis. Nullam ac ultricies ligula, sit amet pretium diam. Cras quis consectetur metus. Nullam eu augue finibus, euismod est vel, tincidunt velit. Integer mattis turpis in massa sollicitudin, at viverra lacus facilisis. Mauris eu odio diam. Nam eget fringilla lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec mauris lectus, tempor et purus et, tristique lobortis ante. Nunc imperdiet accumsan ipsum vel pretium.

Integer eget aliquet leo. Fusce imperdiet lorem id luctus varius. Etiam pharetra ex quis consectetur efficitur. Donec posuere massa ut turpis consectetur, tincidunt vestibulum ante mollis. Vestibulum vel aliquet lorem. Phasellus at pretium urna, ac pharetra mauris. In sit amet gravida purus, eu consequat sapien. Aenean vitae diam mi. Curabitur sit amet neque ac diam aliquet fringilla et quis eros. Aenean congue bibendum euismod. Sed ornare dignissim tempus.

Etiam id dui ac dui fermentum dictum. Aliquam pharetra vel turpis sed mattis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus malesuada justo id mi sodales ultrices. Nullam imperdiet quam a nulla vehicula interdum. Suspendisse potenti. Proin aliquet faucibus purus nec malesuada. Nam id enim sodales, eleifend ante eget, sollicitudin felis. Aliquam sollicitudin, nisl nec eleifend condimentum, nibh magna suscipit quam, nec ultricies arcu justo et justo. Vestibulum sit amet nisi congue, aliquam odio tempus, vulputate elit. Donec faucibus turpis ut semper sollicitudin. Ut at dignissim velit, a luctus mauris. Duis ac leo vel diam rutrum tempus. Nam eu tincidunt felis, ac tempus ante.

Donec nisl sem, porta id suscipit quis, consectetur in est. Maecenas molestie non risus vel pretium. Ut facilisis nec urna sit amet elementum. Maecenas ut massa faucibus, dignissim lorem eu, auctor ex. Aliquam consectetur fermentum lectus. Sed sit amet massa mollis, interdum leo non, ultricies leo. Suspendisse potenti. Nunc tincidunt massa ligula, sit amet lacinia purus elementum quis. Nam at quam gravida, malesuada libero quis, tincidunt lacus.

Integer euismod massa at viverra porttitor. Donec vulputate semper neque quis tempus. Praesent nec ornare erat. Nam sit amet enim urna. Nunc massa leo, pharetra in pellentesque eu, varius maximus velit. Nam pulvinar metus mi, et sagittis lectus tincidunt ac. Aenean condimentum laoreet rutrum. Aenean facilisis nulla libero, a lacinia leo laoreet sed.
        </p>
      </div>
    </>
    
    
  )
}

export default BurgerIngredients;